apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: alamedascalers.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaScaler
    plural: alamedascalers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            enable:
              type: boolean
            policy:
              type: string
            selector:
              type: object
          required:
          - selector
          - enable
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: alamedaresourcepredictions.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaResourcePrediction
    plural: alamedaresourcepredictions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            selector:
              type: object
          required:
          - selector
          type: object
        status:
          properties:
            prediction:
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: alamedarecommendations.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaRecommendation
    plural: alamedarecommendations
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            containers:
              items:
                properties:
                  name:
                    type: string
                  resources:
                    type: object
                required:
                - name
                type: object
              type: array
          required:
          - containers
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
